name: build and test feature branch

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build-feature:
    runs-on: windows-latest
    steps:
      - name: pull and checkout from git repository
        uses: actions/checkout@v3
      - run: |
          echo "pulling and checking out git repository"


      - name: setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install npm packages
        run: npm install

      - name: install latest angular version
        run: npm install -g @angular/cli@latest

      - name: run test and build angular app
        run: |
          ng test --watch=false
          ng build --prod
          echo "run test and build angular app"
